#Configuracion puerto Servidor
server:
  port: 8761
#server:
  #port: ${port:0}

#Nombre a la aplicacion
spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888
#Configurar servidor de eureka
#En donde vamos a tener el servidor de eureka
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    server-url:
#      defaultZone: http://localhost:${server.port}/eureka/

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    renewal-percent-threshold: 0.90